#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-commons-httpclient
Version  : 3.1
Release  : 2
URL      : https://repo1.maven.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
Source0  : https://repo1.maven.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
Source1  : https://repo1.maven.org/maven2/commons-httpclient/commons-httpclient/3.0/commons-httpclient-3.0.pom
Source2  : https://repo1.maven.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-commons-httpclient-data = %{version}-%{release}

%description
Jakarta HttpClient
===========================
Welcome to the HttpClient component of the Jakarta HttpComponents project.

%package data
Summary: data components for the mvn-commons-httpclient package.
Group: Data

%description data
data components for the mvn-commons-httpclient package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-httpclient/commons-httpclient/3.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/commons-httpclient/commons-httpclient/3.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-httpclient/commons-httpclient/3.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/commons-httpclient/commons-httpclient/3.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-httpclient/commons-httpclient/3.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/commons-httpclient/commons-httpclient/3.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/commons-httpclient/commons-httpclient/3.0/commons-httpclient-3.0.pom
/usr/share/java/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
/usr/share/java/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.pom
